/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import tinymce from "@sklinet/strapi-plugin-tinymce/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import navigation from "strapi-plugin-navigation/strapi-admin";
import deploySite from "../../src/plugins/deploy-site/strapi-admin";
import guide from "../../src/plugins/guide/strapi-admin";
import searchIndexer from "../../src/plugins/search-indexer/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    tinymce: tinymce,
    documentation: documentation,
    i18n: i18N,
    "users-permissions": usersPermissions,
    navigation: navigation,
    "deploy-site": deploySite,
    guide: guide,
    "search-indexer": searchIndexer,
  },
});
