name: Deploy testing from master

on:
  push:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - uses: c-hive/gha-yarn-cache@v1
    - run: yarn install --silent
    - run: yarn test

  # NEEDS AZURE IMPLEMENTATION
  # deploy: 
  #   needs: test
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: 14.x
  #   - uses: c-hive/gha-yarn-cache@v1
  #   - run: yarn install --silent
  #   - id: deploy
  #     uses: google-github-actions/deploy-appengine@main
  #     with:
  #       credentials: ${{ secrets.gcp_service_account_key }}
  #       project_id: ${{ secrets.project_id }}

