name: Deploy testing from staging

on:
  push:
    branches: [staging]

env:
  NODE_VERSION: "18.x"

concurrency: testing-environment

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_V4_DATABASE: ${{ secrets.DATABASE_V4_DATABASE }}
      DATABASE_V4_SCHEMA: ${{ secrets.DATABASE_V4_SCHEMA }}
      DATABASE_V4_PORT: ${{ secrets.DATABASE_V4_PORT }}
      DATABASE_V4_HOST: ${{ secrets.DATABASE_V4_HOST }}
      DATABASE_V4_USER: ${{ secrets.DATABASE_V4_USER }}
      DATABASE_V4_PASSWORD: ${{ secrets.DATABASE_V4_PASSWORD }}
      DATABASE_V4_SSL: ${{ secrets.DATABASE_V4_SSL }}
      
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn install --silent

      - name: Debug env variable
        run: echo "DATABASE_V4_DATABASE=${{ secrets.DATABASE_V4_DATABASE }}"

      - run: yarn test

  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    needs: test
    environment: testing
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: yarn build
        run: |
          yarn install --silent
          yarn build
      - name: Deploy to Azure webApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: pof-backend-testing
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
