name: Deploy testing from master

on:
  push:
    branches: [ main ]
    
env:
  #AZURE_WEBAPP_PACKAGE_PATH: ''      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x' 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - uses: c-hive/gha-yarn-cache@v1
    - run: yarn install --silent
    - run: yarn test
    
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    needs: test
    environment: testing
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ env.NODE_VERSION }}
    - name: yarn build
      run: |
        yarn install --silent
        yarn build
    - name: Deploy to Azure webApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        app-settings-json: |
          [
            {
              "name": "STRAPI_DATABASE_CONNECTION_NAME",
              "value": "${{ secrets.STRAPI_DATABASE_CONNECTION_NAME }}",
              "slotSetting": false
            },
            {
              "name": "STRAPI_DATABASE_NAME",
              "value": "${{ secrets.STRAPI_DATABASE_NAME }}",
              "slotSetting": false
            },
            {
              "name": "STRAPI_DATABASE_USERNAME",
              "value": "${{ secrets.STRAPI_DATABASE_USERNAME }}",
              "slotSetting": false
            },
            {
              "name": "STRAPI_DATABASE_PASSWORD",
              "value": "${{ secrets.STRAPI_DATABASE_PASSWORD }}",
              "slotSetting": false
            },
            {
              "name": "ADMIN_JWT_SECRET",
              "value": "${{ secrets.ADMIN_JWT_SECRET }}",
              "slotSetting": false
            },
            {
              "name": "NODE_ENV",
              "value": "testing",
              "slotSetting": false
            }
          ]
        #package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  # NEEDS AZURE IMPLEMENTATION
  # deploy: 
  #   needs: test
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: 14.x
  #   - uses: c-hive/gha-yarn-cache@v1
  #   - run: yarn install --silent
  #   - id: deploy
  #     uses: google-github-actions/deploy-appengine@main
  #     with:
  #       credentials: ${{ secrets.gcp_service_account_key }}
  #       project_id: ${{ secrets.project_id }}

