name: Deploy testing from staging

on:
  push:
    branches: [staging]

env:
  NODE_VERSION: "18.x"

concurrency: testing-environment

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Checkout repository (ensure all history)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures file renames are properly tracked

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: yarn build
        run: |
          yarn install --silent
          yarn build

      - name: Deploy to Azure webApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: pof-backend-testing
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
