name: Deploy production from main
on:
  push:
    branches: [main]
env:
  NODE_VERSION: "18.x"
concurrency: production-environment

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install dependencies and build
        env:
          STRAPI_LICENSE: ${{ secrets.STRAPI_LICENSE }}
        run: |
          yarn install --silent
          yarn build

      - name: Deploy to Azure Web App (run from zip)
        uses: azure/webapps-deploy@v3
        with:
          app-name: pof-backend-production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          clean: true